AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Attendance App Backend (FastAPI + DynamoDB)

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    LoggingConfig:
      LogFormat: Text

Resources:
  # 1. 勤怠データを保存するDynamoDBテーブル
  AttendanceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AttendanceTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE

  # 2. FastAPIを動かすLambda関数
  FastAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Environment:
        Variables:
          TABLE_NAME: !Ref AttendanceTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AttendanceTable
      Events:
        ApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        ApiProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  AttendanceApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"